"""core/db/schema.py — Schema initialization and migration

Wide-table design: the titles table directly inlines star_code, star_name, and magnet info,
completely eliminating stars-titles-magnets triple-table JOINs and cross-table transactions.
Large base64 cover blobs live in the separate title_covers table (1:1 with titles).
"""

from __future__ import annotations

from .connection import _conn


def init_schema(conn=None):
    """Initialize table schema (idempotent)

    conn: if an external connection is passed, use it without closing; otherwise create a new one.
    """
    should_close = conn is None
    conn = conn or _conn()
    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS stars (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL UNIQUE,
                jp_name TEXT,
                handle TEXT,
                code TEXT,
                type TEXT DEFAULT 'solo',
                note TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS titles (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                star_id INTEGER NOT NULL,
                star_code TEXT,
                star_name TEXT,
                code TEXT NOT NULL,
                title TEXT,
                release_date TEXT,
                views INTEGER,
                likes INTEGER,
                resolution TEXT,
                download_url TEXT,
                cover_url TEXT,
                cover_path TEXT,
                charming_intro TEXT,
                jable_m3u8 TEXT,
                jable_cover TEXT,
                release_date_sort TEXT,
                magnet TEXT,
                magnet_hash TEXT,
                all_magnets JSONB,
                user_liked INTEGER DEFAULT 0,
                cover_w INTEGER,
                cover_h INTEGER,
                magnet_status TEXT,
                magnet_checked_at TIMESTAMP,
                magnet_checked_hash TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(star_id, code)
            )
        """)
        # Append columns to existing tables (backward compatibility)
        for col in [
            ("release_date_sort", "TEXT"),
            ("charming_intro", "TEXT"),
            ("star_code", "TEXT"),
            ("star_name", "TEXT"),
            ("magnet", "TEXT"),
            ("magnet_hash", "TEXT"),
            ("all_magnets", "JSONB"),
            ("user_liked", "INTEGER DEFAULT 0"),
            ("cover_w", "INTEGER"),
            ("cover_h", "INTEGER"),
            ("magnet_status", "TEXT"),
            ("magnet_checked_at", "TIMESTAMP"),
            ("magnet_checked_hash", "TEXT"),
        ]:
            conn.execute(f"ALTER TABLE titles ADD COLUMN IF NOT EXISTS {col[0]} {col[1]}")
        conn.execute("""
            CREATE TABLE IF NOT EXISTS title_covers (
                title_id INTEGER PRIMARY KEY REFERENCES titles(id) ON DELETE CASCADE,
                cover_b64 TEXT,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS social_posts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                star_id INTEGER NOT NULL,
                platform TEXT NOT NULL DEFAULT 'x',
                content TEXT NOT NULL,
                post_url TEXT,
                posted_at TIMESTAMP,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (star_id) REFERENCES stars(id),
                UNIQUE(star_id, platform, content)
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS sync_runs (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                trigger TEXT NOT NULL DEFAULT 'manual',
                status TEXT NOT NULL DEFAULT 'running',
                started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                finished_at TIMESTAMP,
                total_new INTEGER DEFAULT 0,
                total_updated INTEGER DEFAULT 0,
                failed_count INTEGER DEFAULT 0,
                error TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS user_events (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                event TEXT NOT NULL,
                code TEXT,
                star_code TEXT,
                meta JSONB
            )
        """)
        conn.execute("CREATE INDEX IF NOT EXISTS idx_user_events_ts ON user_events(ts)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_titles_star ON titles(star_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_titles_code ON titles(code)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_titles_date ON titles(release_date_sort)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_titles_jable ON titles(jable_m3u8)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_social_star ON social_posts(star_id)")
    finally:
        if should_close:
            conn.close()


def backfill_release_date_sort():
    """Backfill release_date_sort column for existing data"""
    conn = _conn()
    try:
        conn.execute(
            """
            UPDATE titles
            SET release_date_sort = CONCAT(
                SPLIT_PART(release_date, '/', 3),
                LPAD(SPLIT_PART(release_date, '/', 1), 2, '0'),
                LPAD(SPLIT_PART(release_date, '/', 2), 2, '0')
            )
            WHERE release_date_sort IS NULL
              AND release_date IS NOT NULL
              AND release_date LIKE %s
            """,
            ("%/%/%",),
        )
    finally:
        conn.close()
